### ISSUE TITLE
Add styles to GitHub pages

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#313]
Current GitHub pages project site is more than poor: https://chaoss.github.io/grimoirelab-sigils

Some CSS magic and layout configuration is needed.

An interesting suggestion by @jsmanrique is including panel screenshot in the template, so users don't need to manually add it to their Markdown content (of course, they always can include more screenshots in content if needed)

**Comment by jsmanrique** [comment]
Perhaps I would ask first to rewrite most of existing documentation to have something like:
- General GrimoireLab panels docs (pages) that would be mainly based in the existing READMEs, Dashboard Customization, FAM and Metrics docs
- Panels collection documentation

What do you think?

Adding CSS should be easy with, for example, Bootstrap and Jeckyll Sass support.

I could try to work on this during following weeks.

**Comment by alpgarcia** [comment]
I would like to have everything rewritten at some point. My main concern is time, just see https://github.com/chaoss/grimoirelab-sigils/pull/304, 9 days waiting for review.

Another reason for not touching those files now is we are moving towards collections, so I'm not sure whether this general documentation makes sense here or we have to move it to a specific general documentation project.

I'd propose to work on this for collections first, as it is easy to make sure new stuff includes the required documentation.

**Comment by alpgarcia** [comment]
Related also to: #171

**Comment by jsmanrique** [comment]
Yes, @alpgarcia, I agree. At some point, we might need to discuss GrimoireLab Sigils repository structure, because it a little chaos now :smile: 

First of all, is it a repository of one collection of panels, or several collections? It seems it's growing to several panels collections, isn't it?:
- `json` (current GrimoireLab _standard_ panels). These are the ones installed also through PyPi packages (see [panels](https://github.com/chaoss/grimoirelab-sigils/tree/master/panels) directory used in the package)
- `dashboards-cauldron`. The legacy panels used in [Cauldron.io](https://cauldron.io). They should be _deprecated_ at some point
- `chaoss-gmd-cde`. The upcoming [CHAOSS GMD Code Development focus area](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md) panels

There are also code and tools related with panels management, that are stored here too:
- `import_panels.sh`
- `src` directory

So, my proposal would be:
- provide meaningful names to the `.json` panels files directories. I would recommend to avoid acronyms. So they could become:
  * rename `json` folder to `sigils`: standard set of GrimoireLab panels. It would be needed to rewrite the symbolic link in `panels` directory (or improve the way the package manages the panels collections), and maybe it could have some undesired effects in current Bitergia deployment infra (but that's Bitergia issue, not GrimoireLab Sigils issue).
  * rename `dashboards-cauldron` to `cauldron`: set of panels used in [Cauldron.io](https://cauldron.io)
  * rename `chaoss-gmd-cde` to `chaoss-gmd-wg-code-development`
- move the tools and scrips to a `utils` directory, with its own README.md or set of `.md` files for documentation
- use `docs` folder for GrimoireLab Sigils and its collections documentation. This mean, that there could be several docs or pages in that folder, and a set of collections with the same names that the ones used in the root directory for the directories of `.json` files.

As `testing` condition we might have the following one (if this can be implemented):
> for each `<collection_name>/<panel_file_name>.json` there **must** be a `docs/_<collection_name>/<panel_file_name>.md` and `docs/assets/images/<collection_name>/<panel_file_name>.jpg`

Comments?

**Comment by sduenas** [comment]
> > for each `<collection_name>/<panel_file_name>.json` there **must** be a `docs/_<collection_name>/<panel_file_name>.md` and `docs/assets/images/<collection_name>/<panel_file_name>.jpg`
> 
> After reading this I think you are the right person to review #304. @sduenas do you know if this check could be hooked somewhere?
> 

With Travis would be possible. It would be like a check that is run by the tests - in the same way it is done with flake8 in other repositories.

**Comment by alpgarcia** [comment]
Ok, so I guess we need two tickets, one for structure and another one for travis. This one should be used for CSS and could be solved even if the others are still WIP. So:

* I've copied structural changes to #315
* I've created a travis related issue at #316

Feel free to edit them if needed.

**Comment by alpgarcia** [comment]
Closed by merging #327 into master.
