### ISSUE TITLE
Facing issue while Creating Kibana Dashboard (table) for "issues last commented by organisation member"

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab-sigils#463]
Hi everyone,

I am facing issue while creating the kibana dashboard for the table with issues last commented by org member

1.I need the position number at which the last org member commented (for example: The last comment given by the org 
   member is at 5th place ,only the last position held by the org member comment).

2.Next the total no. of the comments which is given after the (last org member commented that is from above) -For example 
   from above after 5th position how many comments are given by users,authors etc excluding org member.

3.Therefore point 1 + 2 will be my next field (total comments) which addition of both above.

I hope my issue is clear.Kindly if anyone can let me know how to go about this fields. 
Please comment.
Thank you

**Comment by alpgarcia** [comment]
aFollowing from #460: 
> Hi @alpgarcia ,
> 
> Well, I sorted bucket with issue id and PFA but i could just see issue id's in the table.
> https://user-images.githubusercontent.com/63613092/87786725-c19a6180-c83a-11ea-9fd0-87bda1fc6b89.png
>

That's right, you could use issue title instead or adding another top hits metric to show issue title, just replicating what you did with for `author_org_name` but using issue title. Anyway that's only for enhancing visualization because the thing we want to achieve is having one table row per issue, and that's what you already have.

> For metrics , i sorted with top hit and author org name
> PFA
> 
> https://user-images.githubusercontent.com/63613092/87786870-0625fd00-c83b-11ea-94b6-61263573793c.png
> 

To get the whole list of organization names you should specify a reasonable size to get the organizations names from all available comments for the issue. `100` could be a good initial approach. You can also sort on `grimoire_creation_date` instead.

> I didn't understand the columns hiding part.

Then I recommend you to start playing with the plugin and reading through [its documentation](https://github.com/fbaligand/kibana-enhanced-table):

- Filter table lines based on a computed formula (ex: col0 > 0)
  More documentation [https://github.com/fbaligand/kibana-enhanced-table#computed-column-formula--lines-computed-filter-documentation](url)

- Hide some table columns (ex: 0,1,Col2 Label hides columns 0, 1 and the column labeled 'Col2 Label')
Note that the column label must be written as is (including whitespaces), with no surrounding quotes.
Column labels containing commas are not supported since the comma is used to separate the columns
It is recommended to use column labels to hide columns rather than their indices. Using the 'Split cols' feature, in fact, indices might depend on the global timerange that has been set.


> 1.I need the position number at which the last org member commented (for example: The last comment given by the org
member is at 5th place ,only the last position held by the org member comment).

The only way I know to do it would be including the comment position in the enriched index so you can retrieve it. Even in that case I'm not 100% sure there is a way in Kibana to easily identify the last comment by a specific organization. It's probably possible by means of a filter by organization name and then a bucket sorted by creation date in descending order of size `1`.

You could ask for this as a new FR in grimoirelab-elk or try to add it by yourself. Some pointers:
* Code used for creating the enriched index: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/github2.py
* Index fields documentation: https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_issues.csv

> 2.Next the total no. of the comments which is given after the (last org member commented that is from above) -For example
from above after 5th position how many comments are given by users,authors etc excluding org member.

I think this is to complex to do in Kibana, you would need to identify the org member and then use their name to filter out their comment in a separate query. I don't think there is a way to do it in Kibana.

You could try another approaches as Jupyter Notebook and Pandas on top of the indexes instead of using Kibana, so you can basically code whatever you need by means of pandas data frames and use libraries like plotly to print charts. There are also some alternatives to build dashboards using those:
* https://jupyter.org/
* https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93
* https://plotly.com/dash/


> 3.Therefore point 1 + 2 will be my next field (total comments) which addition of both above.

This is just adding a count metric that will be applied to the bucket.

**Comment by shikha0208** [comment]
Hi @alpgarcia

Thank you for the comments.

So basically this two points are not possible from kibana at present.
```
1.I need the position number at which the last org member commented (for example: The last comment given by the org
member is at 5th place ,only the last position held by the org member comment).

2.Next the total no. of the comments which is given after the (last org member commented that is from above) -For example
from above after 5th position how many comments are given by users,authors etc excluding org member.
```
I am just waiting for other's comment too , if anyone has any other thing to approach.
Otherwise i will not use kibana for these fields.

Kindly give comments,
@valeriocos @zhquan 

Thank you for the time.

**Comment by shikha0208** [comment]
Closing the issue !
As this is not possible from kibana as per the comments.
