### ISSUE TITLE
Jira Timing Panel displays incorrect data for percentiles of issues open

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sigils#466]
The two bar charts at the top right corner of the Jira Timing Dashboard should show the percentiles of time open in days for the tickets created at the given date.
However, it displays the time open of issues that are still in opened state. That means it is always displaying the time from issue creation to now, because they are still opened, and that's why the shape of the bars draws a straight line with decreasing slope as long as we approach to now.

### Some internal details to solve the issue

* The visualizations are built on top of a search for opened tickets. The search should be removed to take into account opened and closed ones.
* The `painless_time_to_now` field is not valid for this. We need another field that checks whether the status is closed or not and computes the time to resolution_date if it is closed.
* I've been checking the data and it's not clear how to identify closed tickets.
* Sometimes they are marked as Closed, Submitted, Delivered...maybe more.
* There is a `resolution_date field`, we could use it to decide if it is resolved. But sometimes it exists with tickets in Open state. For instance the following one has resolution_date from two days ago but it says is still Open and Unresolved: 
![Screenshot_from_2020-07-27_16-54-23](https://user-images.githubusercontent.com/3502941/89879070-a82ed000-dbc2-11ea-83a0-a14da85d4293.png)

* So, how can we identify the actual state of the ticket? Can we trust the resolution date?

## Related PRs

Solved by: https://github.com/chaoss/grimoirelab-elk/pull/928 and https://github.com/chaoss/grimoirelab-sigils/pull/465

**Comment by zhquan** [comment]
To solve this we have to add some extra fields on the enriched indexes to know if the ticket is closed and a scripted field to calculate the time open in days for the tickets.

Use `painless_delay` instead of `painless_time_to_now` and `time_to_close_days` for all Jira visualizations.

New fields:
- `status_category_key`: `data.fields.status.statusCategory.key`
- `is_close`: `1` if `data.fields.status.statusCategory.key` is `done` else `0`

Scripted field:
- `painless_delay`

PR #465 fixes this.
